### ISSUE TITLE
Freyja workflows & tasks updates

### ISSUE THREAD

**Issue by kapsakcj** [theiagen/public_health_bioinformatics#130]
Some Freyja workflows have the WDL workflow & task combined in a single file. They should be separated into separate files for ease of use & maintenance. Additionally some default docker images need to be updated.

feel free to add/edit this list for anything I missed

### TODOs

[Freyja_plot wf](https://github.com/theiagen/public_health_bioinformatics/blob/main/workflows/freyja/wf_freyja_plot.wdl#L44):

- [x] update default docker to `"us-docker.pkg.dev/general-theiagen/staphb/freyja:1.4.4”`
- [x] separate WDL task `freyja_plot_task` to new WDL task file

[Freyja_dashboard wf](https://github.com/theiagen/public_health_bioinformatics/blob/main/workflows/freyja/wf_freyja_dashboard.wdl):

- [x] update default docker to `"us-docker.pkg.dev/general-theiagen/staphb/freyja:1.4.4”`
- [x] separate WDL task `freyja_dashboard_task` to new WDL task file

[Freyja_update](https://github.com/theiagen/public_health_bioinformatics/blob/main/workflows/freyja/wf_freyja_update.wdl):

- [x] update default docker to `"us-docker.pkg.dev/general-theiagen/staphb/freyja:1.4.4”`
- [x] separate WDL task `freyja_dashboard_task` to new WDL task file
- [x] separate WDL task `transfer_files` to new WDL task file specific to transferring freyja files. perhaps call it `transfer_freyja_files` or something since it's specific to the output files from the `freyja update` command
